#!/usr/bin/env php
<?php

if (! file_exists('.env')) {
    if (file_exists('.env.example')) {
        echo "Creating .env file from .env.example" . PHP_EOL;

        if (! copy('.env.example', '.env')) {
            echo "Could not copy .env file" . PHP_EOL;
            return 1;
        }
    } else {
        echo "File .env.example does not exist" . PHP_EOL;
        return 1;
    }
}

passthru("composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev");

passthru("npm install");

passthru("php artisan key:generate --force");

passthru("php artisan mason:setup");

passthru("php artisan mason:deploy");

return 0;
